"""
Otter.ai exported transcript parser (.txt and .docx).
Extracts speaker timestamps, transcript text, metadata, and structured Notion summary blocks.
"""
import os
import re
from typing import Dict, Any, List

try:
    import docx
except ImportError:
    docx = None


def parse_transcript_file(file_path: str) -> Dict[str, Any]:
    """
    Parse an exported Otter.ai transcript file (.txt or .docx).
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Transcript file not found: {file_path}")

    ext = os.path.splitext(file_path)[1].lower()

    if ext == ".docx":
        if docx is None:
            raise ImportError("python-docx package is required to parse .docx files.")
        doc = docx.Document(file_path)
        raw_text = "\n".join([p.text for p in doc.paragraphs if p.text.strip()])
    else:
        with open(file_path, "r", encoding="utf-8", errors="replace") as f:
            raw_text = f.read()

    lines = [line.strip().lstrip('\ufeff\u200b\u200c\u200d') for line in raw_text.splitlines() if line.strip()]
    filename = os.path.basename(file_path)

    # Speaker detection pattern: e.g. "Speaker 1 00:02" or "Raj 10:15"
    speaker_pattern = re.compile(r"^([A-Za-z0-9_\s\-\.\(\)]+)\s+(\d{1,2}:\d{2}(?::\d{2})?)$")

    # Title detection: first non-empty line if not a speaker header, else clean filename
    first_line = lines[0] if lines else ""
    if first_line and not speaker_pattern.match(first_line):
        title = first_line
    else:
        title = filename.rsplit(".", 1)[0].replace("_transcript", "")

    speakers = set()
    dialogue_blocks = []
    current_speaker = None
    current_timestamp = None
    current_speech = []

    for line in lines:
        match = speaker_pattern.match(line)
        if match:
            if current_speaker and current_speech:
                dialogue_blocks.append({
                    "speaker": current_speaker,
                    "timestamp": current_timestamp,
                    "text": " ".join(current_speech)
                })
                current_speech = []
            current_speaker = match.group(1).strip()
            current_timestamp = match.group(2).strip()
            speakers.add(current_speaker)
        else:
            current_speech.append(line)

    if current_speaker and current_speech:
        dialogue_blocks.append({
            "speaker": current_speaker,
            "timestamp": current_timestamp,
            "text": " ".join(current_speech)
        })

    # Notion-ready structured markdown payload
    notion_template = f"""# Interview Summary: {title}

## Metadata
- **Source File**: {filename}
- **Speakers**: {', '.join(sorted(speakers)) if speakers else 'Not identified'}
- **Total Utterances**: {len(dialogue_blocks)}

## Executive Summary
*(Generated by AI Agent from Otter transcript)*

## Key Discussion Points & Action Items
- [ ] Action item 1
- [ ] Action item 2

## Full Dialogue Transcript
"""
    for block in dialogue_blocks:
        notion_template += f"\n**{block['speaker']}** [{block['timestamp']}]\n> {block['text']}\n"

    return {
        "title": title,
        "filename": filename,
        "file_path": file_path,
        "speakers": sorted(list(speakers)),
        "utterance_count": len(dialogue_blocks),
        "raw_text": raw_text,
        "dialogue_blocks": dialogue_blocks,
        "notion_summary_template": notion_template.strip(),
    }
